name: テスト用

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
  push:
    branches:
      - master
    paths:
      - 'test.config'
      - 'test.yml'
  schedule:
    - cron: 0 0 * * 5
  # release:
    # types: [published]
  watch:
    types: started

env:
  REPO_URL: https://github.com/coolsnowwolf/lede
  REPO_BRANCH: master
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: KamiWrt.config
  DIY_P1_SH: diy-before-feed.sh
  DIY_P2_SH: diy-after-feed.sh
  UPLOAD_PACKAGES_DIR: true
  UPLOAD_FIRMWARE: true
  UPLOAD_TO_ARTIFACTS: false
  UPLOAD_TO_REALEASE: true
  TELEGRAM_NOTIFICATION: true
  WECHAT_NOTIFICATION: false
  DELETE_OLD_REALEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: 获取当前日期
      id: date
      run: |
        date=$(date +'%y%m%d')
        echo "DATE=$date" >> $GITHUB_ENV
        echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
        echo "START_SECOND=$(date +"%s")" >> $GITHUB_ENV
    
    - name: 移除workflow运行
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 3

    - name: 计算编译时长
      id: length
      run: |
        a=$(date +"%s")
        timeLength=$[$(date +"%s")-${{env.START_SECOND}}]
        timeHour=$[$timeLength/3600]
        timeMin=$[($timeLength-$timeHour*3600)/60]
        echo "TIME_HOUR=$timeHour" >> $GITHUB_ENV
        echo "TIME_MIN=$timeMin" >> $GITHUB_ENV
        a=$timeHour
        b=$timeMin

    - name: Telegram推送
      if: env.TELEGRAM_NOTIFICATION == 'true' && !cancelled()
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT_ID }}
        token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        args: テストメッセージ！%0D%0A時間：${{env.TIME_HOUR}}時${{env.TIME_MIN}}分
